services:
  backend:
    build:
      context: ./publisher_register
    ports:
      - "8000:8000"  # Ánh xạ cổng 8000 trên máy chủ đến cổng 8000 trong container
    networks:
      - app-network
    environment:
      SPRING_APPLICATION_NAME: publisher_register
      SPRING_DATA_MONGODB_URI: mongodb+srv://admin:admin123@cluster0.eptvm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      SPRING_DATA_MONGODB_DATABASE: publisher_register_db
      SERVER_PORT: 8000   # Cong de ung dung lang nghe

  frontend:
    build:
      context: ./publisher-register-ui
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
